# Generated by Django 2.2.10 on 2020-06-09 08:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_age', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='От какого возраста')),
                ('to_age', models.IntegerField(default=99, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='До какого возраста')),
                ('name', models.CharField(max_length=155, verbose_name='Имя возростной категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Удален')),
            ],
            options={
                'verbose_name': 'Возростная категория',
                'verbose_name_plural': 'Возрастные категории',
                'get_latest_by': ['-created_at', '-updated_at'],
                'select_on_save': True,
                'unique_together': {('created_at', 'id'), ('from_age', 'to_age')},
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название программы')),
                ('is_active', models.BooleanField(default=False, verbose_name='Статус программы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Удален')),
            ],
            options={
                'verbose_name': 'Список Программ',
                'verbose_name_plural': 'Список Программ',
                'get_latest_by': ['-created_at', '-updated_at'],
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='ProgramAgeRelationsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Удален')),
                ('question_plus_variants_cnt', models.IntegerField(default=0)),
                ('text_missing_words_cnt', models.IntegerField(default=0)),
                ('image_plus_text_cnt', models.IntegerField(default=0)),
                ('image_plus_variants_cnt', models.IntegerField(default=0)),
                ('audio_plus_variants_cnt', models.IntegerField(default=0)),
                ('video_plus_variants_cnt', models.IntegerField(default=0)),
                ('build_sentence_cnt', models.IntegerField(default=0)),
                ('age_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='age_id', to='programs.Age')),
                ('program_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_id', to='programs.Program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='ages',
            field=models.ManyToManyField(related_name='programs', through='programs.ProgramAgeRelationsTable', to='programs.Age'),
        ),
        migrations.AddIndex(
            model_name='programagerelationstable',
            index=models.Index(fields=['program_id', 'age_id'], name='programs_pr_program_d328e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('created_at', 'id')},
        ),
    ]
